service: 
  build: 
    context: ./server
    dockerfile: Dockerfile.production
  volumes: 
    - /app/node_modules
    - ./server/src:/app/src
  ports: 
    - "8080:8081"
ui: 
  build:
    context: ./client
    dockerfile: Dockerfile.production
  volumes: 
    - /app/node_modules
    - ./client/app
  ports: 
    - "3000:3000" 